import Providers from './Providers'
import Header from './components/header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'IMDB Yagaw',
  description: 'Generated by IMDB YG',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    


      <body className={inter.className}>
        <Providers>
          {/* Header */}
          <Header/>
          {/* Navbar */}

          {/* SearchBox */}
          {children}
        </Providers>

      </body>
    </html>
  )
}
